# Site settings
title: the Fipster
title_addon: Personal developer blog of Felix Reisch.

tagline: >
  Hi. I'm Felix a professional and passionate software engineer 
  located in North-Rhine-Westphalia, Germany. 
  My main objectives are writing SOLID software using mostly C#.
  Beside that I also enjoy writing some Typescript, Ruby, Python, Elixir or Prolog. 
  Let's be honest, in the end it all boils down to allocations, conditions and loops.

description: >
  Hi. I'm Felix a professional and passionate software engineer 
  located in North-Rhine-Westphalia, Germany. 
  My main objectives are writing SOLID software using mostly C#.
  Beside that I also enjoy writing some Typescript, Ruby, Python, Elixir or Prolog. 
  Let's be honest, in the end it all boils down to allocations, conditions and loops.
  In my spare time I like to play around with everything that contains 
  the letters IoT and needs some soldering.

url: "https://www.thefipster.com"
title_image: "https://secure.gravatar.com/avatar/026db6b54f988e00fd9f49ac7fb59707?s=500&d=mm"
post_limit: 5
show_rss: false
show_tags: false

# Integrations
# google_analytics: "UA-157542757-1"
# disqus_account: thefipster
# addthis_id: ra-5e37edd373c65640

# Social usernames/URLs
email: felix.reisch@live.de
github_username:  thefipster
linkedin_link: https://de.linkedin.com/in/felix-reisch-a5a334116
xing_link: https://www.xing.com/profile/Felix_Reisch/

# Footer
footer_left: > 
  Made with 
  <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>, 
  <a href="https://github.com/jacobtomlinson/carte-noire" target="_blank" rel="noopener">Carte Noire</a> 
  and <i class="icon-heart"></i>

footer_right: >
  Proudly hosted on 
  <a href="https://github.com/thefipster/thefipster.github.io" target="_blank" rel="noopener">Github</a>

# SEO
author:
  twitter: thefipster
twitter:
  username: thefipster
logo: https://www.thefipster.com/favicons/apple-touch-icon.png
social:
  name: Felix Reisch
  links:
    - https://twitter.com/thefipster
#webmaster_verifications:
#  google: 1234
#  bing: 1234
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234
lang: en_US
keywords: 
  - Felix
  - Reisch
  - Fipster
  - software

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag