# Site settings
title: the Fipster
title_addon: Developerish blog of Felix Reisch

tagline: >
  Hi. I'm Felix a professional and passionate software engineer 
  located in North-Rhine-Westphalia, Germany. 
  My main objectives are writing SOLID software using mostly C#.
  Beside that I also enjoy writing some Typescript, Ruby, Python, Elixir or Prolog. 
  Let's be honest, in the end it all boils down to allocations, conditions and loops.
  In my spare time I like to play around with everything that contains 
  the letters IoT and needs some soldering.

description: >
  Hi. I'm Felix a professional and passionate software engineer 
  located in North-Rhine-Westphalia, Germany. 
  My main objectives are writing SOLID software using mostly C#.

url: "https://www.thefipster.com"
title_image: "https://secure.gravatar.com/avatar/026db6b54f988e00fd9f49ac7fb59707?s=500&d=mm"

email: felix.reisch@live.de
github_username:  thefipster
linkedin_link: https://de.linkedin.com/in/felix-reisch-a5a334116
xing_link: https://www.xing.com/profile/Felix_Reisch/

post_limit: 5

# SEO
author:
  twitter: thefipster
twitter:
  username: thefipster
logo: https://www.thefipster.com/favicons/apple-touch-icon.png
social:
  name: Felix Reisch
  links:
    - https://twitter.com/thefipster
keywords: 
  - Felix
  - Reisch
  - Fipster
  - software
  - engineer
  - c#
  - Elixir
  - Python
  - jekyll
  - Prolog
  - SOLID
  - software
  - architecture
  - design

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-email-protect